"""auto vote

Revision ID: dfb63eb7b23f
Revises: a0af3016f8bf
Create Date: 2021-12-29 23:33:24.292082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb63eb7b23f'
down_revision = 'a0af3016f8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.add_column('posts', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('posts', 'title ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title ', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'title')
    op.drop_table('votes')
    # ### end Alembic commands ###
